--INSERT INTO MASTER.CLIENTES(id,nombre, email) VALUES (1,'Alfa','alfa@yahoo.com');
--INSERT INTO MASTER.CLIENTES(id,nombre, email) VALUES (2,'Beta','beta@yahoo.com');
--INSERT INTO MASTER.CLIENTES(id,nombre, email) VALUES (3,'Gamma','gam@yahoo.com');